# This is a basic workflow to help you get started with Actions

name: Send msg to Teams

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  webhook: https://studntnu.webhook.office.com/webhookb2/3ead07fd-2966-4a7e-ac5e-19f88fb5ff77@09a10672-822f-4467-a5ba-5bb375967c05/IncomingWebhook/3f5b74d5cd884cb9bb24bf53ec4da1e7/3011f2d9-c189-4900-87e9-3739018254f0
  date: `date "+%Y%m%d-%H%M%S"`

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Send"
  Send:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: env
        run: github

      # Send msg to teams
      - name: Send msg to Teams
        run: |
          curl --location --request POST $webhook --header 'Content-Type: application/json' --data-raw '{"@type": "MessageCard","@context": "http://schema.org/extensions","themeColor": "0076D7","summary": "${{ github.event.head_commit.message }}","sections": [{"activityTitle": "GitHub auto message","activitySubtitle": "$date","activityImage": "https://github.githubassets.com/images/modules/logos_page/Octocat.png","facts": [{"name": "Repository","value": "${{ github.repository }}"},{"name": "Event","value": "${{ github.event.name }}"},{"name": "Message","value": "${{ github.event.head_commit.message }}"}],"markdown": true}]}'
